setup: &setup
  - uses: actions/checkout@v3
  - uses: docker-practice/actions-setup-docker@master
    timeout-minutes: 12
  - run: |
      pip install --upgrade pip
      pip install --upgrade poetry
      poetry install --all-extras

on: push

name: ci

jobs:
  linting:
    runs-on: ubuntu-latest
    steps: &setup
      - run: poetry run flake8

  testing:
    runs-on: ubuntu-latest
    steps: &setup
      - run: poetry run pytest -rA -m "not slow"

  e2e:
    runs-on: ubuntu-latest
    steps: &setup
      - run: poetry run pytest -rA -m slow
